var cardsDb = [{
    name: "trump",
    urlFirstImg: "https://middleeasttransparent.com/wp-content/uploads/2017/10/TUMP.jpg",
    urlSecondImg: "https://middleeasttransparent.com/wp-content/uploads/2017/10/TUMP.jpg",
}, {
    name: "Merkel",
    urlFirstImg: "", 
    urlSecondImg: "",  
}, {
    name: "Brian",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "Einstein",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "Messi",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "Fyre",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}]

