var cardsDb = [{
    name: "trump",
    urlFirstImg: "img/trump.jpg",
    urlSecondImg: "img/maga.jpg",
}, {
    name: "Merkel",
    urlFirstImg: "img/angela.jpg", 
    urlSecondImg: "",  
}, {
    name: "Brian",
    urlFirstImg: "img/brian.jpg", 
    urlSecondImg: "", 
}, {
    name: "Einstein",
    urlFirstImg: "img/einstein.jpg", 
    urlSecondImg: "", 
}, {
    name: "Messi",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "Fyre",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}, {
    name: "",
    urlFirstImg: "", 
    urlSecondImg: "", 
}]

